# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt1011.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Movie(object):
    def setupUi(self, Movie):
        Movie.setObjectName("Movie")
        Movie.resize(621, 846)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../Pictures/movie-time-poster-vintage-cinema-260nw-1480643543.webp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Movie.setWindowIcon(icon)
        self.Creditinfo = QtWidgets.QStackedWidget(Movie)
        self.Creditinfo.setGeometry(QtCore.QRect(0, 0, 621, 861))
        self.Creditinfo.setObjectName("Creditinfo")
        self.window = QtWidgets.QWidget()
        self.window.setObjectName("window")
        self.labelWIN = QtWidgets.QLabel(self.window)
        self.labelWIN.setGeometry(QtCore.QRect(-6, -5, 631, 851))
        self.labelWIN.setText("")
        self.labelWIN.setPixmap(QtGui.QPixmap("../../Downloads/Pastel Tryout Cheerleading Poster (3).jpg"))
        self.labelWIN.setScaledContents(True)
        self.labelWIN.setObjectName("labelWIN")
        self.choosemovie = QtWidgets.QComboBox(self.window)
        self.choosemovie.setGeometry(QtCore.QRect(150, 610, 331, 51))
        self.choosemovie.setStyleSheet("\n"
"background-color: rgb(255, 170, 127);\n"
"\n"
"font: 16pt \"Alfphabet\";")
        self.choosemovie.setObjectName("choosemovie")
        self.choosemovie.addItem("")
        self.choosemovie.addItem("")
        self.choosemovie.addItem("")
        self.choosemovie.addItem("")
        self.Next = QtWidgets.QPushButton(self.window)
        self.Next.setGeometry(QtCore.QRect(480, 770, 111, 41))
        self.Next.setStyleSheet("background-color: rgb(255, 255, 127);\n"
"font: 12pt \"Alfphabet\";")
        self.Next.setObjectName("Next")
        self.Creditinfo.addWidget(self.window)
        self.Movie1 = QtWidgets.QWidget()
        self.Movie1.setObjectName("Movie1")
        self.label_TENET = QtWidgets.QLabel(self.Movie1)
        self.label_TENET.setGeometry(QtCore.QRect(-6, -5, 631, 851))
        self.label_TENET.setText("")
        self.label_TENET.setPixmap(QtGui.QPixmap("../../Downloads/Pastel Tryout Cheerleading Poster (7).jpg"))
        self.label_TENET.setScaledContents(True)
        self.label_TENET.setObjectName("label_TENET")
        self.SelectDate1 = QtWidgets.QComboBox(self.Movie1)
        self.SelectDate1.setGeometry(QtCore.QRect(60, 470, 341, 41))
        self.SelectDate1.setStyleSheet("\n"
"background-color: rgb(242, 255, 151);\n"
"\n"
"font: 20pt \"Alfphabet\";\n"
"\n"
"\n"
"\n"
"")
        self.SelectDate1.setObjectName("SelectDate1")
        self.SelectDate1.addItem("")
        self.SelectDate1.addItem("")
        self.SelectDate1.addItem("")
        self.SelectDate1.addItem("")
        self.SelectDate1.addItem("")
        self.SelectDate1.addItem("")
        self.SelectDate1.addItem("")
        self.SelectDate1.addItem("")
        self.SelectDate1.addItem("")
        self.SelectTime1 = QtWidgets.QComboBox(self.Movie1)
        self.SelectTime1.setGeometry(QtCore.QRect(60, 530, 521, 41))
        self.SelectTime1.setStyleSheet("font: 20pt \"Alfphabet\";\n"
"background-color: rgb(255, 237, 170);")
        self.SelectTime1.setObjectName("SelectTime1")
        self.SelectTime1.addItem("")
        self.SelectTime1.addItem("")
        self.SelectTime1.addItem("")
        self.SelectTime1.addItem("")
        self.SelectTime1.addItem("")
        self.SelectTime1.addItem("")
        self.Next_2 = QtWidgets.QPushButton(self.Movie1)
        self.Next_2.setGeometry(QtCore.QRect(480, 780, 111, 31))
        self.Next_2.setStyleSheet("background-color: rgb(255, 255, 127);\n"
"font: 12pt \"Alfphabet\";")
        self.Next_2.setObjectName("Next_2")
        self.Back = QtWidgets.QPushButton(self.Movie1)
        self.Back.setGeometry(QtCore.QRect(50, 780, 101, 31))
        self.Back.setStyleSheet("background-color: rgb(255, 255, 127);\n"
"font: 12pt \"Alfphabet\";")
        self.Back.setObjectName("Back")
        self.Creditinfo.addWidget(self.Movie1)
        self.Movie2 = QtWidgets.QWidget()
        self.Movie2.setObjectName("Movie2")
        self.label_FROZEN = QtWidgets.QLabel(self.Movie2)
        self.label_FROZEN.setGeometry(QtCore.QRect(-6, -5, 631, 851))
        self.label_FROZEN.setText("")
        self.label_FROZEN.setPixmap(QtGui.QPixmap("../../Downloads/Pastel Tryout Cheerleading Poster (8).jpg"))
        self.label_FROZEN.setScaledContents(True)
        self.label_FROZEN.setObjectName("label_FROZEN")
        self.SelectDate2 = QtWidgets.QComboBox(self.Movie2)
        self.SelectDate2.setGeometry(QtCore.QRect(60, 590, 331, 41))
        self.SelectDate2.setStyleSheet("\n"
"background-color: rgb(242, 255, 151);\n"
"\n"
"font: 20pt \"Alfphabet\";")
        self.SelectDate2.setObjectName("SelectDate2")
        self.SelectDate2.addItem("")
        self.SelectDate2.addItem("")
        self.SelectDate2.addItem("")
        self.SelectDate2.addItem("")
        self.SelectDate2.addItem("")
        self.SelectDate2.addItem("")
        self.SelectDate2.addItem("")
        self.SelectDate2.addItem("")
        self.SelectDate2.addItem("")
        self.SelectTime2 = QtWidgets.QComboBox(self.Movie2)
        self.SelectTime2.setGeometry(QtCore.QRect(60, 640, 521, 41))
        self.SelectTime2.setStyleSheet("\n"
"background-color: rgb(242, 255, 151);\n"
"\n"
"font: 20pt \"Alfphabet\";")
        self.SelectTime2.setObjectName("SelectTime2")
        self.SelectTime2.addItem("")
        self.SelectTime2.addItem("")
        self.SelectTime2.addItem("")
        self.SelectTime2.addItem("")
        self.SelectTime2.addItem("")
        self.Next_3 = QtWidgets.QPushButton(self.Movie2)
        self.Next_3.setGeometry(QtCore.QRect(480, 780, 111, 31))
        self.Next_3.setStyleSheet("background-color: rgb(255, 255, 127);\n"
"font: 12pt \"Alfphabet\";")
        self.Next_3.setObjectName("Next_3")
        self.Back_2 = QtWidgets.QPushButton(self.Movie2)
        self.Back_2.setGeometry(QtCore.QRect(60, 780, 91, 31))
        self.Back_2.setStyleSheet("background-color: rgb(255, 255, 127);\n"
"font: 12pt \"Alfphabet\";")
        self.Back_2.setObjectName("Back_2")
        self.Creditinfo.addWidget(self.Movie2)
        self.SCREEN1 = QtWidgets.QWidget()
        self.SCREEN1.setObjectName("SCREEN1")
        self.SCREEN1_2 = QtWidgets.QLabel(self.SCREEN1)
        self.SCREEN1_2.setGeometry(QtCore.QRect(-6, -5, 631, 851))
        self.SCREEN1_2.setText("")
        self.SCREEN1_2.setPixmap(QtGui.QPixmap("../../Downloads/Pastel Tryout Cheerleading Poster (17.jpg"))
        self.SCREEN1_2.setScaledContents(True)
        self.SCREEN1_2.setObjectName("SCREEN1_2")
        self.checkBox = QtWidgets.QCheckBox(self.SCREEN1)
        self.checkBox.setGeometry(QtCore.QRect(130, 300, 51, 20))
        self.checkBox.setStyleSheet("background-color: rgb(255, 255, 127);\n"
"font: 8pt \"Alfphabet\";")
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.SCREEN1)
        self.checkBox_2.setGeometry(QtCore.QRect(200, 300, 51, 20))
        self.checkBox_2.setStyleSheet("background-color: rgb(255, 255, 127);\n"
"font: 8pt \"Alfphabet\";")
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(self.SCREEN1)
        self.checkBox_3.setGeometry(QtCore.QRect(270, 300, 51, 20))
        self.checkBox_3.setStyleSheet("background-color: rgb(255, 255, 127);\n"
"font: 8pt \"Alfphabet\";")
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_4 = QtWidgets.QCheckBox(self.SCREEN1)
        self.checkBox_4.setGeometry(QtCore.QRect(130, 350, 51, 20))
        self.checkBox_4.setStyleSheet("background-color: rgb(255, 255, 127);\n"
"font: 8pt \"Alfphabet\";")
        self.checkBox_4.setObjectName("checkBox_4")
        self.checkBox_5 = QtWidgets.QCheckBox(self.SCREEN1)
        self.checkBox_5.setGeometry(QtCore.QRect(130, 390, 51, 20))
        self.checkBox_5.setStyleSheet("background-color: rgb(255, 255, 127);\n"
"font: 8pt \"Alfphabet\";")
        self.checkBox_5.setObjectName("checkBox_5")
        self.checkBox_6 = QtWidgets.QCheckBox(self.SCREEN1)
        self.checkBox_6.setGeometry(QtCore.QRect(130, 430, 51, 20))
        self.checkBox_6.setStyleSheet("background-color: rgb(255, 255, 127);\n"
"font: 8pt \"Alfphabet\";")
        self.checkBox_6.setObjectName("checkBox_6")
        self.checkBox_7 = QtWidgets.QCheckBox(self.SCREEN1)
        self.checkBox_7.setGeometry(QtCore.QRect(200, 350, 51, 20))
        self.checkBox_7.setStyleSheet("background-color: rgb(255, 255, 127);\n"
"font: 8pt \"Alfphabet\";")
        self.checkBox_7.setObjectName("checkBox_7")
        self.checkBox_8 = QtWidgets.QCheckBox(self.SCREEN1)
        self.checkBox_8.setGeometry(QtCore.QRect(200, 390, 51, 20))
        self.checkBox_8.setStyleSheet("background-color: rgb(255, 255, 127);\n"
"font: 8pt \"Alfphabet\";")
        self.checkBox_8.setObjectName("checkBox_8")
        self.checkBox_9 = QtWidgets.QCheckBox(self.SCREEN1)
        self.checkBox_9.setGeometry(QtCore.QRect(130, 470, 51, 20))
        self.checkBox_9.setStyleSheet("background-color: rgb(255, 255, 127);\n"
"font: 8pt \"Alfphabet\";")
        self.checkBox_9.setObjectName("checkBox_9")
        self.checkBox_10 = QtWidgets.QCheckBox(self.SCREEN1)
        self.checkBox_10.setGeometry(QtCore.QRect(340, 300, 51, 20))
        self.checkBox_10.setStyleSheet("background-color: rgb(255, 255, 127);\n"
"font: 8pt \"Alfphabet\";")
        self.checkBox_10.setObjectName("checkBox_10")
        self.checkBox_11 = QtWidgets.QCheckBox(self.SCREEN1)
        self.checkBox_11.setGeometry(QtCore.QRect(270, 350, 51, 20))
        self.checkBox_11.setStyleSheet("background-color: rgb(255, 255, 127);\n"
"font: 8pt \"Alfphabet\";")
        self.checkBox_11.setObjectName("checkBox_11")
        self.checkBox_12 = QtWidgets.QCheckBox(self.SCREEN1)
        self.checkBox_12.setGeometry(QtCore.QRect(340, 350, 51, 20))
        self.checkBox_12.setStyleSheet("background-color: rgb(255, 255, 127);\n"
"font: 8pt \"Alfphabet\";")
        self.checkBox_12.setObjectName("checkBox_12")
        self.checkBox_13 = QtWidgets.QCheckBox(self.SCREEN1)
        self.checkBox_13.setGeometry(QtCore.QRect(200, 430, 51, 20))
        self.checkBox_13.setStyleSheet("background-color: rgb(255, 255, 127);\n"
"font: 8pt \"Alfphabet\";")
        self.checkBox_13.setObjectName("checkBox_13")
        self.checkBox_14 = QtWidgets.QCheckBox(self.SCREEN1)
        self.checkBox_14.setGeometry(QtCore.QRect(200, 470, 51, 20))
        self.checkBox_14.setStyleSheet("background-color: rgb(255, 255, 127);\n"
"font: 8pt \"Alfphabet\";")
        self.checkBox_14.setObjectName("checkBox_14")
        self.checkBox_15 = QtWidgets.QCheckBox(self.SCREEN1)
        self.checkBox_15.setGeometry(QtCore.QRect(270, 390, 51, 20))
        self.checkBox_15.setStyleSheet("background-color: rgb(255, 255, 127);\n"
"font: 8pt \"Alfphabet\";")
        self.checkBox_15.setObjectName("checkBox_15")
        self.checkBox_16 = QtWidgets.QCheckBox(self.SCREEN1)
        self.checkBox_16.setGeometry(QtCore.QRect(270, 430, 51, 20))
        self.checkBox_16.setStyleSheet("background-color: rgb(255, 255, 127);\n"
"font: 8pt \"Alfphabet\";")
        self.checkBox_16.setObjectName("checkBox_16")
        self.checkBox_17 = QtWidgets.QCheckBox(self.SCREEN1)
        self.checkBox_17.setGeometry(QtCore.QRect(270, 470, 51, 20))
        self.checkBox_17.setStyleSheet("background-color: rgb(255, 255, 127);\n"
"font: 8pt \"Alfphabet\";")
        self.checkBox_17.setObjectName("checkBox_17")
        self.checkBox_18 = QtWidgets.QCheckBox(self.SCREEN1)
        self.checkBox_18.setGeometry(QtCore.QRect(340, 390, 51, 20))
        self.checkBox_18.setStyleSheet("background-color: rgb(255, 255, 127);\n"
"font: 8pt \"Alfphabet\";")
        self.checkBox_18.setObjectName("checkBox_18")
        self.checkBox_19 = QtWidgets.QCheckBox(self.SCREEN1)
        self.checkBox_19.setGeometry(QtCore.QRect(340, 430, 51, 20))
        self.checkBox_19.setStyleSheet("background-color: rgb(255, 255, 127);\n"
"font: 8pt \"Alfphabet\";")
        self.checkBox_19.setObjectName("checkBox_19")
        self.checkBox_20 = QtWidgets.QCheckBox(self.SCREEN1)
        self.checkBox_20.setGeometry(QtCore.QRect(340, 470, 51, 20))
        self.checkBox_20.setStyleSheet("background-color: rgb(255, 255, 127);\n"
"font: 8pt \"Alfphabet\";")
        self.checkBox_20.setObjectName("checkBox_20")
        self.Next_4 = QtWidgets.QPushButton(self.SCREEN1)
        self.Next_4.setGeometry(QtCore.QRect(490, 780, 101, 31))
        self.Next_4.setStyleSheet("background-color: rgb(255, 255, 127);\n"
"font: 12pt \"Alfphabet\";")
        self.Next_4.setObjectName("Next_4")
        self.checkBox_41 = QtWidgets.QCheckBox(self.SCREEN1)
        self.checkBox_41.setGeometry(QtCore.QRect(420, 470, 51, 20))
        self.checkBox_41.setStyleSheet("background-color: rgb(255, 255, 127);\n"
"font: 8pt \"Alfphabet\";")
        self.checkBox_41.setObjectName("checkBox_41")
        self.checkBox_42 = QtWidgets.QCheckBox(self.SCREEN1)
        self.checkBox_42.setGeometry(QtCore.QRect(420, 300, 51, 20))
        self.checkBox_42.setStyleSheet("background-color: rgb(255, 255, 127);\n"
"font: 8pt \"Alfphabet\";")
        self.checkBox_42.setObjectName("checkBox_42")
        self.checkBox_43 = QtWidgets.QCheckBox(self.SCREEN1)
        self.checkBox_43.setGeometry(QtCore.QRect(420, 350, 51, 20))
        self.checkBox_43.setStyleSheet("background-color: rgb(255, 255, 127);\n"
"font: 8pt \"Alfphabet\";")
        self.checkBox_43.setObjectName("checkBox_43")
        self.checkBox_44 = QtWidgets.QCheckBox(self.SCREEN1)
        self.checkBox_44.setGeometry(QtCore.QRect(420, 390, 51, 20))
        self.checkBox_44.setStyleSheet("background-color: rgb(255, 255, 127);\n"
"font: 8pt \"Alfphabet\";")
        self.checkBox_44.setObjectName("checkBox_44")
        self.checkBox_45 = QtWidgets.QCheckBox(self.SCREEN1)
        self.checkBox_45.setGeometry(QtCore.QRect(420, 430, 51, 20))
        self.checkBox_45.setStyleSheet("background-color: rgb(255, 255, 127);\n"
"font: 8pt \"Alfphabet\";")
        self.checkBox_45.setObjectName("checkBox_45")
        self.Back_3 = QtWidgets.QPushButton(self.SCREEN1)
        self.Back_3.setGeometry(QtCore.QRect(50, 770, 91, 31))
        self.Back_3.setStyleSheet("background-color: rgb(255, 255, 127);\n"
"font: 12pt \"Alfphabet\";")
        self.Back_3.setObjectName("Back_3")
        self.totalprice1 = QtWidgets.QLabel(self.SCREEN1)
        self.totalprice1.setGeometry(QtCore.QRect(230, 680, 161, 51))
        self.totalprice1.setStyleSheet("background-color: rgb(255, 170, 127);\n"
"font: 8pt \"Alfphabet\";")
        self.totalprice1.setText("")
        self.totalprice1.setObjectName("totalprice1")
        self.Creditinfo.addWidget(self.SCREEN1)
        self.Screen2 = QtWidgets.QWidget()
        self.Screen2.setObjectName("Screen2")
        self.SCREEN2 = QtWidgets.QLabel(self.Screen2)
        self.SCREEN2.setGeometry(QtCore.QRect(-6, -5, 631, 851))
        self.SCREEN2.setText("")
        self.SCREEN2.setPixmap(QtGui.QPixmap("../../Downloads/Pastel Tryout Cheerleading Poster (17.jpg"))
        self.SCREEN2.setScaledContents(True)
        self.SCREEN2.setObjectName("SCREEN2")
        self.checkBox_21 = QtWidgets.QCheckBox(self.Screen2)
        self.checkBox_21.setGeometry(QtCore.QRect(160, 470, 51, 20))
        self.checkBox_21.setStyleSheet("background-color: rgb(255, 255, 127);\n"
"font: 8pt \"Alfphabet\";")
        self.checkBox_21.setObjectName("checkBox_21")
        self.checkBox_22 = QtWidgets.QCheckBox(self.Screen2)
        self.checkBox_22.setGeometry(QtCore.QRect(100, 510, 51, 20))
        self.checkBox_22.setStyleSheet("background-color: rgb(255, 255, 127);\n"
"font: 8pt \"Alfphabet\";")
        self.checkBox_22.setObjectName("checkBox_22")
        self.checkBox_23 = QtWidgets.QCheckBox(self.Screen2)
        self.checkBox_23.setGeometry(QtCore.QRect(110, 430, 51, 20))
        self.checkBox_23.setStyleSheet("background-color: rgb(255, 255, 127);\n"
"font: 8pt \"Alfphabet\";")
        self.checkBox_23.setObjectName("checkBox_23")
        self.checkBox_24 = QtWidgets.QCheckBox(self.Screen2)
        self.checkBox_24.setGeometry(QtCore.QRect(260, 470, 51, 20))
        self.checkBox_24.setStyleSheet("background-color: rgb(255, 255, 127);\n"
"font: 8pt \"Alfphabet\";")
        self.checkBox_24.setObjectName("checkBox_24")
        self.checkBox_25 = QtWidgets.QCheckBox(self.Screen2)
        self.checkBox_25.setGeometry(QtCore.QRect(160, 380, 51, 20))
        self.checkBox_25.setStyleSheet("background-color: rgb(255, 255, 127);\n"
"font: 8pt \"Alfphabet\";")
        self.checkBox_25.setObjectName("checkBox_25")
        self.checkBox_26 = QtWidgets.QCheckBox(self.Screen2)
        self.checkBox_26.setGeometry(QtCore.QRect(210, 510, 51, 20))
        self.checkBox_26.setStyleSheet("background-color: rgb(255, 255, 127);\n"
"font: 8pt \"Alfphabet\";")
        self.checkBox_26.setObjectName("checkBox_26")
        self.checkBox_27 = QtWidgets.QCheckBox(self.Screen2)
        self.checkBox_27.setGeometry(QtCore.QRect(110, 330, 51, 20))
        self.checkBox_27.setStyleSheet("background-color: rgb(255, 255, 127);\n"
"font: 8pt \"Alfphabet\";")
        self.checkBox_27.setObjectName("checkBox_27")
        self.checkBox_28 = QtWidgets.QCheckBox(self.Screen2)
        self.checkBox_28.setGeometry(QtCore.QRect(210, 430, 51, 20))
        self.checkBox_28.setStyleSheet("background-color: rgb(255, 255, 127);\n"
"font: 8pt \"Alfphabet\";")
        self.checkBox_28.setObjectName("checkBox_28")
        self.checkBox_29 = QtWidgets.QCheckBox(self.Screen2)
        self.checkBox_29.setGeometry(QtCore.QRect(260, 380, 51, 20))
        self.checkBox_29.setStyleSheet("background-color: rgb(255, 255, 127);\n"
"font: 8pt \"Alfphabet\";")
        self.checkBox_29.setObjectName("checkBox_29")
        self.checkBox_30 = QtWidgets.QCheckBox(self.Screen2)
        self.checkBox_30.setGeometry(QtCore.QRect(210, 330, 51, 20))
        self.checkBox_30.setStyleSheet("background-color: rgb(255, 255, 127);\n"
"font: 8pt \"Alfphabet\";")
        self.checkBox_30.setObjectName("checkBox_30")
        self.checkBox_31 = QtWidgets.QCheckBox(self.Screen2)
        self.checkBox_31.setGeometry(QtCore.QRect(320, 510, 51, 20))
        self.checkBox_31.setStyleSheet("background-color: rgb(255, 255, 127);\n"
"font: 8pt \"Alfphabet\";")
        self.checkBox_31.setObjectName("checkBox_31")
        self.checkBox_32 = QtWidgets.QCheckBox(self.Screen2)
        self.checkBox_32.setGeometry(QtCore.QRect(370, 470, 51, 20))
        self.checkBox_32.setStyleSheet("background-color: rgb(255, 255, 127);\n"
"font: 8pt \"Alfphabet\";")
        self.checkBox_32.setObjectName("checkBox_32")
        self.checkBox_33 = QtWidgets.QCheckBox(self.Screen2)
        self.checkBox_33.setGeometry(QtCore.QRect(310, 430, 51, 20))
        self.checkBox_33.setStyleSheet("background-color: rgb(255, 255, 127);\n"
"font: 8pt \"Alfphabet\";")
        self.checkBox_33.setObjectName("checkBox_33")
        self.checkBox_34 = QtWidgets.QCheckBox(self.Screen2)
        self.checkBox_34.setGeometry(QtCore.QRect(370, 380, 51, 20))
        self.checkBox_34.setStyleSheet("background-color: rgb(255, 255, 127);\n"
"font: 8pt \"Alfphabet\";")
        self.checkBox_34.setObjectName("checkBox_34")
        self.checkBox_35 = QtWidgets.QCheckBox(self.Screen2)
        self.checkBox_35.setGeometry(QtCore.QRect(310, 330, 51, 20))
        self.checkBox_35.setStyleSheet("background-color: rgb(255, 255, 127);\n"
"font: 8pt \"Alfphabet\";")
        self.checkBox_35.setObjectName("checkBox_35")
        self.checkBox_36 = QtWidgets.QCheckBox(self.Screen2)
        self.checkBox_36.setGeometry(QtCore.QRect(430, 510, 51, 20))
        self.checkBox_36.setStyleSheet("background-color: rgb(255, 255, 127);\n"
"font: 8pt \"Alfphabet\";")
        self.checkBox_36.setObjectName("checkBox_36")
        self.checkBox_37 = QtWidgets.QCheckBox(self.Screen2)
        self.checkBox_37.setGeometry(QtCore.QRect(480, 470, 51, 20))
        self.checkBox_37.setStyleSheet("background-color: rgb(255, 255, 127);\n"
"font: 8pt \"Alfphabet\";")
        self.checkBox_37.setObjectName("checkBox_37")
        self.checkBox_38 = QtWidgets.QCheckBox(self.Screen2)
        self.checkBox_38.setGeometry(QtCore.QRect(410, 430, 51, 20))
        self.checkBox_38.setStyleSheet("background-color: rgb(255, 255, 127);\n"
"font: 8pt \"Alfphabet\";")
        self.checkBox_38.setObjectName("checkBox_38")
        self.checkBox_39 = QtWidgets.QCheckBox(self.Screen2)
        self.checkBox_39.setGeometry(QtCore.QRect(470, 380, 51, 20))
        self.checkBox_39.setStyleSheet("background-color: rgb(255, 255, 127);\n"
"font: 8pt \"Alfphabet\";")
        self.checkBox_39.setObjectName("checkBox_39")
        self.checkBox_40 = QtWidgets.QCheckBox(self.Screen2)
        self.checkBox_40.setGeometry(QtCore.QRect(410, 330, 51, 20))
        self.checkBox_40.setStyleSheet("background-color: rgb(255, 255, 127);\n"
"font: 8pt \"Alfphabet\";")
        self.checkBox_40.setObjectName("checkBox_40")
        self.Next_5 = QtWidgets.QPushButton(self.Screen2)
        self.Next_5.setGeometry(QtCore.QRect(490, 780, 91, 31))
        self.Next_5.setStyleSheet("background-color: rgb(255, 255, 127);\n"
"font: 12pt \"Alfphabet\";")
        self.Next_5.setObjectName("Next_5")
        self.Back_4 = QtWidgets.QPushButton(self.Screen2)
        self.Back_4.setGeometry(QtCore.QRect(50, 780, 91, 31))
        self.Back_4.setStyleSheet("background-color: rgb(255, 255, 127);\n"
"font: 12pt \"Alfphabet\";")
        self.Back_4.setObjectName("Back_4")
        self.totalprice2 = QtWidgets.QLabel(self.Screen2)
        self.totalprice2.setGeometry(QtCore.QRect(250, 670, 141, 51))
        self.totalprice2.setStyleSheet("background-color: rgb(255, 170, 127);\n"
"font: 8pt \"Alfphabet\";")
        self.totalprice2.setText("")
        self.totalprice2.setObjectName("totalprice2")
        self.Creditinfo.addWidget(self.Screen2)
        self.payment = QtWidgets.QWidget()
        self.payment.setObjectName("payment")
        self.PayCREDIT = QtWidgets.QLabel(self.payment)
        self.PayCREDIT.setGeometry(QtCore.QRect(-6, -5, 631, 851))
        self.PayCREDIT.setText("")
        self.PayCREDIT.setPixmap(QtGui.QPixmap("../../Downloads/Pastel Tryout Cheerleading Poster (12.jpg"))
        self.PayCREDIT.setScaledContents(True)
        self.PayCREDIT.setObjectName("PayCREDIT")
        self.pushButton_4 = QtWidgets.QPushButton(self.payment)
        self.pushButton_4.setGeometry(QtCore.QRect(100, 610, 181, 41))
        self.pushButton_4.setStyleSheet("font: 8pt \"Alfphabet\";\n"
"background-color: rgb(170, 255, 127);")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.payment)
        self.pushButton_5.setGeometry(QtCore.QRect(330, 610, 191, 41))
        self.pushButton_5.setStyleSheet("font: 8pt \"Alfphabet\";\n"
"background-color: rgb(170, 255, 127);")
        self.pushButton_5.setObjectName("pushButton_5")
        self.textEdit = QtWidgets.QTextEdit(self.payment)
        self.textEdit.setGeometry(QtCore.QRect(160, 210, 331, 41))
        self.textEdit.setObjectName("textEdit")
        self.mobileNo = QtWidgets.QTextEdit(self.payment)
        self.mobileNo.setGeometry(QtCore.QRect(160, 210, 321, 41))
        self.mobileNo.setObjectName("mobileNo")
        self.Credit = QtWidgets.QPushButton(self.payment)
        self.Credit.setGeometry(QtCore.QRect(90, 610, 201, 41))
        self.Credit.setStyleSheet("background-color: rgb(170, 255, 127);\n"
"font: 9pt \"Alfphabet\";")
        self.Credit.setObjectName("Credit")
        self.payment_2 = QtWidgets.QPushButton(self.payment)
        self.payment_2.setGeometry(QtCore.QRect(340, 610, 191, 41))
        self.payment_2.setStyleSheet("background-color: rgb(170, 255, 127);\n"
"font: 9pt \"Alfphabet\";")
        self.payment_2.setObjectName("payment_2")
        self.Next_6 = QtWidgets.QPushButton(self.payment)
        self.Next_6.setGeometry(QtCore.QRect(490, 780, 101, 31))
        self.Next_6.setStyleSheet("background-color: rgb(255, 255, 127);\n"
"font: 12pt \"Alfphabet\";")
        self.Next_6.setObjectName("Next_6")
        self.Creditinfo.addWidget(self.payment)
        self.Qrcode = QtWidgets.QWidget()
        self.Qrcode.setObjectName("Qrcode")
        self.PayQR = QtWidgets.QLabel(self.Qrcode)
        self.PayQR.setGeometry(QtCore.QRect(-6, -5, 631, 861))
        self.PayQR.setText("")
        self.PayQR.setPixmap(QtGui.QPixmap("../../Downloads/Pastel Tryout Cheerleading Poster 11.jpg"))
        self.PayQR.setScaledContents(True)
        self.PayQR.setObjectName("PayQR")
        self.Next_7 = QtWidgets.QPushButton(self.Qrcode)
        self.Next_7.setGeometry(QtCore.QRect(482, 787, 101, 31))
        self.Next_7.setStyleSheet("background-color: rgb(255, 255, 127);\n"
"font: 9pt \"Alfphabet\";")
        self.Next_7.setObjectName("Next_7")
        self.Back_6 = QtWidgets.QPushButton(self.Qrcode)
        self.Back_6.setGeometry(QtCore.QRect(60, 790, 91, 31))
        self.Back_6.setStyleSheet("background-color: rgb(255, 255, 127);\n"
"font: 12pt \"Alfphabet\";")
        self.Back_6.setObjectName("Back_6")
        self.Creditinfo.addWidget(self.Qrcode)
        self.Debit = QtWidgets.QWidget()
        self.Debit.setObjectName("Debit")
        self.label_9 = QtWidgets.QLabel(self.Debit)
        self.label_9.setGeometry(QtCore.QRect(-6, -5, 631, 851))
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("../../Downloads/Pastel Tryout Cheerleading Poster (16.jpg"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.CardHoldername = QtWidgets.QTextEdit(self.Debit)
        self.CardHoldername.setGeometry(QtCore.QRect(140, 370, 341, 31))
        self.CardHoldername.setObjectName("CardHoldername")
        self.Numberofcard = QtWidgets.QTextEdit(self.Debit)
        self.Numberofcard.setGeometry(QtCore.QRect(110, 470, 401, 41))
        self.Numberofcard.setObjectName("Numberofcard")
        self.Next_8 = QtWidgets.QPushButton(self.Debit)
        self.Next_8.setGeometry(QtCore.QRect(490, 780, 93, 28))
        self.Next_8.setStyleSheet("background-color: rgb(255, 255, 127);\n"
"font: 9pt \"Alfphabet\";")
        self.Next_8.setObjectName("Next_8")
        self.CreditDAY = QtWidgets.QTextEdit(self.Debit)
        self.CreditDAY.setGeometry(QtCore.QRect(60, 590, 201, 31))
        self.CreditDAY.setObjectName("CreditDAY")
        self.CreditTime = QtWidgets.QTextEdit(self.Debit)
        self.CreditTime.setGeometry(QtCore.QRect(360, 590, 151, 31))
        self.CreditTime.setObjectName("CreditTime")
        self.Back_7 = QtWidgets.QPushButton(self.Debit)
        self.Back_7.setGeometry(QtCore.QRect(60, 780, 93, 28))
        self.Back_7.setStyleSheet("background-color: rgb(255, 255, 127);\n"
"font: 12pt \"Alfphabet\";")
        self.Back_7.setObjectName("Back_7")
        self.Creditinfo.addWidget(self.Debit)
        self.Ticket = QtWidgets.QWidget()
        self.Ticket.setObjectName("Ticket")
        self.ticket1 = QtWidgets.QLabel(self.Ticket)
        self.ticket1.setGeometry(QtCore.QRect(-10, -10, 641, 1091))
        self.ticket1.setText("")
        self.ticket1.setPixmap(QtGui.QPixmap("../../Downloads/Pastel Tryout Cheerleading Poster (20.jpg"))
        self.ticket1.setScaledContents(True)
        self.ticket1.setObjectName("ticket1")
        self.DONE = QtWidgets.QPushButton(self.Ticket)
        self.DONE.setGeometry(QtCore.QRect(450, 740, 121, 41))
        self.DONE.setStyleSheet("background-color: rgb(255, 255, 127);\n"
"font: 9pt \"Alfphabet\";")
        self.DONE.setObjectName("DONE")
        self.MOVIENAME88888 = QtWidgets.QLabel(self.Ticket)
        self.MOVIENAME88888.setGeometry(QtCore.QRect(60, 350, 331, 51))
        self.MOVIENAME88888.setStyleSheet("background-color: rgb(255, 170, 127);color:rgb(0,0,0);\n"
"font: 8pt \"Alfphabet\";")
        self.MOVIENAME88888.setText("")
        self.MOVIENAME88888.setObjectName("MOVIENAME88888")
        self.Seat = QtWidgets.QLabel(self.Ticket)
        self.Seat.setGeometry(QtCore.QRect(110, 620, 161, 101))
        self.Seat.setStyleSheet("background-color: rgb(255, 170, 127);\n"
"font: 8pt \"Alfphabet\";")
        self.Seat.setText("")
        self.Seat.setObjectName("Seat")
        self.SHOWTIME1 = QtWidgets.QLabel(self.Ticket)
        self.SHOWTIME1.setGeometry(QtCore.QRect(60, 410, 331, 51))
        self.SHOWTIME1.setStyleSheet("background-color: rgb(255, 170, 127);\n"
"font: 8pt \"Alfphabet\";")
        self.SHOWTIME1.setText("")
        self.SHOWTIME1.setObjectName("SHOWTIME1")
        self.label = QtWidgets.QLabel(self.Ticket)
        self.label.setGeometry(QtCore.QRect(60, 470, 331, 51))
        self.label.setStyleSheet("background-color: rgb(255, 170, 127);\n"
"font: 8pt \"Alfphabet\";")
        self.label.setText("")
        self.label.setObjectName("label")
        self.Creditinfo.addWidget(self.Ticket)

        self.retranslateUi(Movie)
        self.Creditinfo.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Movie)

        self.Next.clicked.connect(self.go1)
        self.Next_2.clicked.connect(self.go2)
        self.Next_3.clicked.connect(self.go3)
        self.Next_4.clicked.connect(self.go4)
        self.Next_5.clicked.connect(self.go5)
        self.Next_6.clicked.connect(self.go6)
        self.Next_7.clicked.connect(self.go7)
        self.Next_8.clicked.connect(self.go8)
        self.DONE.clicked.connect(self.go9)
        self.Back.clicked.connect(self.go10)
        self.Back_2.clicked.connect(self.go11)
        self.Back_3.clicked.connect(self.go12)
        self.Back_4.clicked.connect(self.go13)
        self.Back_6.clicked.connect(self.go15)
        self.Back_7.clicked.connect(self.go16)
        self.Credit.clicked.connect(self.go17)#
        self.payment_2.clicked.connect(self.go18)#

        #SCEEN1
        self.checkBox.clicked.connect(self.seatseat)
        self.checkBox_10.clicked.connect(self.seatseat)
        self.checkBox_11.clicked.connect(self.seatseat)
        self.checkBox_12.clicked.connect(self.seatseat)
        self.checkBox_13.clicked.connect(self.seatseat)
        self.checkBox_14.clicked.connect(self.seatseat)
        self.checkBox_15.clicked.connect(self.seatseat)
        self.checkBox_16.clicked.connect(self.seatseat)
        self.checkBox_17.clicked.connect(self.seatseat)
        self.checkBox_18.clicked.connect(self.seatseat)
        self.checkBox_19.clicked.connect(self.seatseat)
        self.checkBox_2.clicked.connect(self.seatseat)
        self.checkBox_20.clicked.connect(self.seatseat)
        self.checkBox_3.clicked.connect(self.seatseat)
        self.checkBox_4.clicked.connect(self.seatseat)
        self.checkBox_41.clicked.connect(self.seatseat)
        self.checkBox_42.clicked.connect(self.seatseat)
        self.checkBox_43.clicked.connect(self.seatseat)
        self.checkBox_44.clicked.connect(self.seatseat)
        self.checkBox_45.clicked.connect(self.seatseat)
        self.checkBox_5.clicked.connect(self.seatseat)
        self.checkBox_6.clicked.connect(self.seatseat)
        self.checkBox_7.clicked.connect(self.seatseat)
        self.checkBox_8.clicked.connect(self.seatseat)
        self.checkBox_9.clicked.connect(self.seatseat)
        #SCEEN2
        self.checkBox_21.clicked.connect(self.seatseatseat)
        self.checkBox_22.clicked.connect(self.seatseatseat)
        self.checkBox_23.clicked.connect(self.seatseatseat)
        self.checkBox_24.clicked.connect(self.seatseatseat)
        self.checkBox_25.clicked.connect(self.seatseatseat)
        self.checkBox_26.clicked.connect(self.seatseatseat)
        self.checkBox_27.clicked.connect(self.seatseatseat)
        self.checkBox_28.clicked.connect(self.seatseatseat)
        self.checkBox_29.clicked.connect(self.seatseatseat)
        self.checkBox_30.clicked.connect(self.seatseatseat)
        self.checkBox_31.clicked.connect(self.seatseatseat)
        self.checkBox_32.clicked.connect(self.seatseatseat)
        self.checkBox_33.clicked.connect(self.seatseatseat)
        self.checkBox_34.clicked.connect(self.seatseatseat)
        self.checkBox_35.clicked.connect(self.seatseatseat)
        self.checkBox_36.clicked.connect(self.seatseatseat)
        self.checkBox_37.clicked.connect(self.seatseatseat)
        self.checkBox_38.clicked.connect(self.seatseatseat)
        self.checkBox_39.clicked.connect(self.seatseatseat)
        self.checkBox_40.clicked.connect(self.seatseatseat)


##        movie = self.choosemovie.currentText()
##        time = self.SelectTime1.currentText()
        
        self.choosemovie.activated.connect(self.moviename)
        self.SelectDate1.activated.connect(self.DAY)
        self.SelectTime1.activated.connect(self.TIME)
#        self.choosemovie.activated.connect(self.movienamename)
        self.SelectDate2.activated.connect(self.DAYDAY)
        self.SelectTime2.activated.connect(self.TIMETIME)

    
 
    def go1(self):
        name = self.choosemovie.currentText()
        if name == "FROZEN II":
            self.Creditinfo.setCurrentIndex(2)
        if name == "TENET":
            self.Creditinfo.setCurrentIndex(1)
 
            
    def go2(self):
        name = self.SelectTime1.currentText()
        if name == "11:30 / Theatre 1":
            self.Creditinfo.setCurrentIndex(3)
        if name == "12:30 / Theatre 2":
            self.Creditinfo.setCurrentIndex(4)
        if name == "14:30 / Theatre 1":
            self.Creditinfo.setCurrentIndex(3)
        if name == "17:30 / Theatre 1":
            self.Creditinfo.setCurrentIndex(3)
        if name == "20:00 / Theatre 2":
            self.Creditinfo.setCurrentIndex(4)
    
    def go3(self):
        name = self.SelectTime2.currentText()
        if name == "11:30 / Theatre 2":
            self.Creditinfo.setCurrentIndex(4)
        if name == "14:30 / Theatre 2":
            self.Creditinfo.setCurrentIndex(4)
        if name == "17:30 / Theatre 2":
            self.Creditinfo.setCurrentIndex(4)
        if name == "20:00 / Theatre 1":
            self.Creditinfo.setCurrentIndex(3)
            
    def go4(self):
        self.Creditinfo.setCurrentIndex(5)
        
    def go5(self):
        self.Creditinfo.setCurrentIndex(5)
    def go6(self):
        self.Creditinfo.setCurrentIndex(6)        
    def go7(self):
        self.Creditinfo.setCurrentIndex(8)
    def go8(self):
        self.Creditinfo.setCurrentIndex(8)
    def go9(self):
        self.Creditinfo.setCurrentIndex(0)
    def go10(self):
        self.Creditinfo.setCurrentIndex(0)
    def go11(self):
        self.Creditinfo.setCurrentIndex(0)
    def go12(self):
        self.Creditinfo.setCurrentIndex(1)#TE
    def go13(self):
        self.Creditinfo.setCurrentIndex(2)#FR
    def go15(self):
        self.Creditinfo.setCurrentIndex(5)
    def go16(self):
        self.Creditinfo.setCurrentIndex(5)
    def go17(self):
        self.Creditinfo.setCurrentIndex(7)#PAYMENT
    def go18(self):
        self.Creditinfo.setCurrentIndex(6)
        
    
#SCEEN1
    def seatseat(self):
        total = 0
        seat = 0
        seat_show = []
        if self.checkBox.isChecked():
            seat_show.append("E1")
            seat +=1
        if self.checkBox_10.isChecked():
            seat_show.append("E4")
            seat +=1
        if self.checkBox_11.isChecked():
            seat_show.append("D3")
            seat +=1
        if self.checkBox_12.isChecked():
            seat_show.append("D4")
            seat +=1
        if self.checkBox_13.isChecked():
            seat_show.append("B2")
            seat +=1
        if self.checkBox_14.isChecked():
            seat_show.append("A2")
            seat +=1
        if self.checkBox_15.isChecked():
            seat_show.append("C3")
            seat +=1
        if self.checkBox_16.isChecked():
            seat_show.append("B3")
            seat +=1
        if self.checkBox_17.isChecked():
            seat_show.append("A3")
            seat +=1
        if self.checkBox_18.isChecked():
            seat_show.append("C4")
            seat +=1
        if self.checkBox_19.isChecked():
            seat_show.append("B4")
            seat +=1
        if self.checkBox_2.isChecked():
            seat_show.append("E2")
            seat +=1
        if self.checkBox_20.isChecked():
            seat_show.append("A4")#13
            seat +=1
        if self.checkBox_3.isChecked():
            seat_show.append("E3")
            seat +=1
        if self.checkBox_4.isChecked():
            seat_show.append("Df1")
            seat +=1
        if self.checkBox_41.isChecked():
            seat_show.append("A5")
            seat +=1
        if self.checkBox_42.isChecked():
            seat_show.append("E5")
            seat +=1
        if self.checkBox_43.isChecked():
            seat_show.append("D5")
            seat +=1
        if self.checkBox_44.isChecked():
            seat_show.append("C5")
            seat +=1
        if self.checkBox_45.isChecked():
            seat_show.append("B5")
            seat +=1
        if self.checkBox_5.isChecked():
            seat_show.append("C1")
            seat +=1
        if self.checkBox_6.isChecked():
            seat_show.append("B1")
            seat +=1
        if self.checkBox_7.isChecked():
            seat_show.append("D2")
            seat +=1
        if self.checkBox_8.isChecked():
            seat_show.append("C2")
            seat +=1
        if self.checkBox_9.isChecked():
            seat_show.append("A1")
            seat +=1

        total = seat*300
        self.totalprice1.setText("   "+str(total))
        self.Seat.setText(str(seat_show))


##        if self.checkBox.isChecked():
##            seat_show.append("E1")
##        if self.checkBox_10.isChecked():
##            seat_show.append("E4")
##        if self.checkBox_11.isChecked():
##            seat_show.append("D3")
##        if self.checkBox_12.isChecked():
##            seat_show.append("D4")
##        if self.checkBox_13.isChecked():
##            seat_show.append("B2")
##        if self.checkBox_14.isChecked():
##            seat_show.append("A2")
##        if self.checkBox_15.isChecked():
##            seat_show.append("C3")
##        if self.checkBox_16.isChecked():
##            seat_show.append("B3")
##        if self.checkBox_17.isChecked():
##            seat_show.append("A3")
##        if self.checkBox_18.isChecked():
##            seat_show.append("C4")
##        if self.checkBox_19.isChecked():
##            seat_show.append("B4")
##        if self.checkBox_2.isChecked():
##            seat_show.append("E2")
##        if self.checkBox_20.isChecked():
##            seat_show.append("A4")
##        if self.checkBox_3.isChecked():
##            seat_show.append("E3")
##        if self.checkBox_4.isChecked():
##            seat_show.append("D1")
##        if self.checkBox_41.isChecked():
##            seat_show.append("A5")
##        if self.checkBox_42.isChecked():
##            seat_show.append("E5")
##        if self.checkBox_43.isChecked():
##            seat_show.append("D5")
##        if self.checkBox_44.isChecked():
##            seat_show.append("C5")
##        if self.checkBox_45.isChecked():
##            seat_show.append("B5")
##        if self.checkBox_5.isChecked():
##            seat_show.append("C1")
##        if self.checkBox_6.isChecked():
##            seat_show.append("B1")
##        if self.checkBox_7.isChecked():
##            seat_show.append("D2")
##        if self.checkBox_8.isChecked():
##            seat_show.append("C2")
##        if self.checkBox_9.isChecked():
##            seat_show.append("A1")
           
        #self.Seat.setText(seat_show)
        
        
#SCREEN2       
    def seatseatseat(self):
        total = 0
        seat = 0
        seat_show = []
        if self.checkBox_21.isChecked():
            seat_show.append("B1")
            seat +=1
        if self.checkBox_22.isChecked():
            seat_show.append("A1")
            seat +=1
        if self.checkBox_24.isChecked():
            seat_show.append("C1")
            seat +=1
        if self.checkBox_25.isChecked():
            seat_show.append("B2")
            seat +=1
        if self.checkBox_26.isChecked():
            seat_show.append("D1")
            seat +=1
        if self.checkBox_27.isChecked():
            seat_show.append("A2")
            seat +=1
        if self.checkBox_28.isChecked():
            seat_show.append("E1")
            seat +=1
        if self.checkBox_29.isChecked():
            seat_show.append("C2")
            seat +=1
        if self.checkBox_30.isChecked():
            seat_show.append("D2")
            seat +=1
        if self.checkBox_31.isChecked():
            seat_show.append("E2")
            seat +=1
        if self.checkBox_31.isChecked():
            seat_show.append("A3")
            seat +=1
        if self.checkBox_32.isChecked():
            seat_show.append("B3")#13
            seat +=1
        if self.checkBox_33.isChecked():
            seat_show.append("C3")
            seat +=1
        if self.checkBox_34.isChecked():
            seat_show.append("D3")
            seat +=1
        if self.checkBox_35.isChecked():
            seat_show.append("E3")
            seat +=1
        if self.checkBox_36.isChecked():
            seat_show.append("A4")
            seat +=1
        if self.checkBox_37.isChecked():
            seat_show.append("B4")
            seat +=1
        if self.checkBox_38.isChecked():
            seat_show.append("C4")
            seat +=1
        if self.checkBox_39.isChecked():
            seat_show.append("D4")
            seat +=1
        if self.checkBox_40.isChecked():
            seat_show.append("E4")
            seat +=1

        total = seat*300
        self.totalprice2.setText("   "+str(total))
        self.Seat.setText(str(seat_show))

##        if self.checkBox_21.isChecked():
##            seat_show.append("B1")
##        if self.checkBox_22.isChecked():
##            seat_show.append("A1")
##        if self.checkBox_23.isChecked():
##            seat_show.append("C1")
##        if self.checkBox_24.isChecked():
##            seat_show.append("B2")
##        if self.checkBox_25.isChecked():
##            seat_show.append("D1")
##        if self.checkBox_26.isChecked():
##            seat_show.append("A2")
##        if self.checkBox_27.isChecked():
##            seat_show.append("E1")
##        if self.checkBox_28.isChecked():
##             seat_show.append("C2")
##        if self.checkBox_29.isChecked():
##            seat_show.append("D2")
##        if self.checkBox_30.isChecked():
##            seat_show.append("E2")
##        if self.checkBox_31.isChecked():
##            seat_show.append("A3")
##        if self.checkBox_32.isChecked():
##            seat_show.append("B3")
##        if self.checkBox_33.isChecked():
##            seat_show.append("C3")
##        if self.checkBox_34.isChecked():
##            seat_show.append("D3")
##        if self.checkBox_35.isChecked():
##            seat_show.append("E3")
##        if self.checkBox_36.isChecked():
##            seat_show.append("A4")
##        if self.checkBox_37.isChecked():
##            seat_show.append("B4")
##        if self.checkBox_38.isChecked():
##            seat_show.append("C4")
##        if self.checkBox_39.isChecked():
##           self.Seat.setText(" "+"D4")
##        if self.checkBox_40.isChecked():
##           self.Seat.setText(" "+"E4")
##        
   
#RESULT
        #self.choosemovie.activated.connect(self.moviename)
    def moviename(self):
        self.moviename1 = self.choosemovie.currentText()
        self.MOVIENAME88888.setText("  "+str(self.moviename1))
          
        #self.SelectDate1.activated.connect(self.DAY)
    def DAY(self):
        self.DAY1 = self.SelectDate1.currentText()
        self.SHOWTIME1.setText("  "+self.DAY1)

        #self.SelectTime1.activated.connect(self.TIME)
    def TIME(self):
        self.TIME1 = self.SelectTime1.currentText()
        self.label.setText("  "+self.TIME1)

        #self.choosemovie.activated.connect(self.movienamename)
##    def movienamename(self):
##        self.moviename2 = self.choosemovie.currentText()
##        self.MOVIENAME88888.setText("  "+str(self.moviename2))
##        
##        #self.SelectDate2.activated.connect(self.DAYDAY)
    def DAYDAY(self):
        print("test")
        self.DAYDAY1 = self.SelectDate2.currentText()
        self.SHOWTIME1.setText("  "+self.DAYDAY1)
##        
##        #self.SelectTime2.activated.connect(self.TIMETIME)
    def TIMETIME(self):
        self.TIMETIME1 = self.SelectTime2.currentText()
        self.label.setText("  "+self.TIMETIME1)


        
##
###SEAT111111
##        self.checkBox.clicked.connect(self.sit)
##        self.checkBox_10.clicked.connect(self.sit)
##        self.checkBox_11.clicked.connect(self.sit)
##        self.checkBox_12.clicked.connect(self.sit)
##        self.checkBox_13.clicked.connect(self.sit)
##        self.checkBox_14.clicked.connect(self.sit)
##        self.checkBox_15.clicked.connect(self.sit)
##        self.checkBox_16.clicked.connect(self.sit)
##        self.checkBox_17.clicked.connect(self.sit)
##        self.checkBox_18.clicked.connect(self.sit)
##        self.checkBox_19.clicked.connect(self.sit)
##        self.checkBox_2.clicked.connect(self.sit)
##        self.checkBox_20.clicked.connect(self.sit)
##        self.checkBox_3.clicked.connect(self.sit)
##        self.checkBox_4.clicked.connect(self.sit)
##        self.checkBox_41.clicked.connect(self.sit)
##        self.checkBox_42.clicked.connect(self.sit)
##        self.checkBox_43.clicked.connect(self.sit)
##        self.checkBox_44.clicked.connect(self.sit)
##        self.checkBox_45.clicked.connect(self.sit)
##        self.checkBox_5.clicked.connect(self.sit)
##        self.checkBox_6.clicked.connect(self.sit)
##        self.checkBox_7.clicked.connect(self.sit)
##        self.checkBox_8.clicked.connect(self.sit)
##        self.checkBox_9.clicked.connect(self.sit)
##    def sit(self):
##        sit_seat = 0
##        if self.checkBox.isChecked():
##            sit_seat +=1
##        if self.checkBox_10.isChecked():
##            sit_seat +=1
##        if self.checkBox_11.isChecked():
##            sit_seat +=1
##        if self.checkBox_12.isChecked():
##            sit_seat +=1
##        if self.checkBox_13.isChecked():
##            sit_seat +=1
##        if self.checkBox_14.isChecked():
##            sit_seat +=1
##        if self.checkBox_15.isChecked():
##            sit_seat +=1
##        if self.checkBox_16.isChecked():
##            sit_seat +=1
##        if self.checkBox_17.isChecked():
##            sit_seat +=1
##        if self.checkBox_18.isChecked():
##            sit_seat +=1
##        if self.checkBox_19.isChecked():
##            sit_seat +=1
##        if self.checkBox_2.isChecked():
##            sit_seat +=1
##        if self.checkBox_20.isChecked():
##            sit_seat +=1
##        if self.checkBox_3.isChecked():
##            sit_seat +=1
##        if self.checkBox_4.isChecked():
##            sit_seat +=1
##        if self.checkBox_41.isChecked():
##            sit_seat +=1
##        if self.checkBox_42.isChecked():
##            sit_seat +=1
##        if self.checkBox_43.isChecked():
##            sit_seat +=1
##        if self.checkBox_44.isChecked():
##            sit_seat +=1
##        if self.checkBox_45.isChecked():
##            sit_seat +=1
##        if self.checkBox_5.isChecked():
##            sit_seat +=1
##        if self.checkBox_6.isChecked():
##            sit_seat +=1
##        if self.checkBox_7.isChecked():
##            sit_seat +=1
##        if self.checkBox_8.isChecked():
##            sit_seat +=1
##        if self.checkBox_9.isChecked():
##            sit_seat +=1
##
###SCREEN22
##        self.checkBox_21.clicked.connect(self.sitsit)
##        self.checkBox_22.clicked.connect(self.sitsit)
##        self.checkBox_23.clicked.connect(self.sitsit)
##        self.checkBox_24.clicked.connect(self.sitsit)
##        self.checkBox_25.clicked.connect(self.sitsit)
##        self.checkBox_26.clicked.connect(self.sitsit)
##        self.checkBox_27.clicked.connect(self.sitsit)
##        self.checkBox_28.clicked.connect(self.sitsit)
##        self.checkBox_29.clicked.connect(self.sitsit)
##        self.checkBox_30.clicked.connect(self.sitsit)
##        self.checkBox_31.clicked.connect(self.sitsit)
##        self.checkBox_32.clicked.connect(self.sitsit)
##        self.checkBox_33.clicked.connect(self.sitsit)
##        self.checkBox_34.clicked.connect(self.sitsit)
##        self.checkBox_35.clicked.connect(self.sitsit)
##        self.checkBox_36.clicked.connect(self.sitsit)
##        self.checkBox_37.clicked.connect(self.sitsit)
##        self.checkBox_38.clicked.connect(self.sitsit)
##        self.checkBox_39.clicked.connect(self.sitsit)
##        self.checkBox_40.clicked.connect(self.sitsit)
##
##    def sitsit(self):
##        sitsit_seat = 0
##        if self.checkBox_21.isChecked():
##            sitsit_seat +=1
##        if self.checkBox_22.isChecked():
##            sitsit_seat +=1
##        if self.checkBox_23.isChecked():
##            sitsit_seat +=1
##        if self.checkBox_24.isChecked():
##            sitsit_seat +=1
##        if self.checkBox_25.isChecked():
##            sitsit_seat +=1
##        if self.checkBox_26.isChecked():
##            sitsit_seat +=1
##        if self.checkBox_27.isChecked():
##            sitsit_seat +=1
##        if self.checkBox_28.isChecked():
##            sitsit_seat +=1
##        if self.checkBox_29.isChecked():
##            sitsit_seat +=1
##        if self.checkBox_30.isChecked():
##            sitsit_seat +=1
##        if self.checkBox_31.isChecked():
##            sitsit_seat +=1
##        if self.checkBox_32.isChecked():
##            sitsit_seat +=1
##        if self.checkBox_33.isChecked():
##            sitsit_seat +=1
##        if self.checkBox_34.isChecked():
##            sitsit_seat +=1
##        if self.checkBox_35.isChecked():
##            sitsit_seat +=1
##        if self.checkBox_36.isChecked():
##            sitsit_seat +=1
##        if self.checkBox_37.isChecked():
##            sitsit_seat +=1
##        if self.checkBox_38.isChecked():
##            sitsit_seat +=1
##        if self.checkBox_39.isChecked():
##            sitsit_seat +=1
##        if self.checkBox_40.isChecked():
##            sitsit_seat +=1


        

      
        
##################################################################
    def retranslateUi(self, Movie):
        _translate = QtCore.QCoreApplication.translate
        Movie.setWindowTitle(_translate("Movie", "Movie"))
        self.choosemovie.setItemText(0, _translate("Movie", "CHOOSE MOVIE"))
        self.choosemovie.setItemText(1, _translate("Movie", "TENET"))
        self.choosemovie.setItemText(2, _translate("Movie", "FROZEN II"))
        self.choosemovie.setItemText(3, _translate("Movie", "..."))
        self.Next.setText(_translate("Movie", "NEXT"))
        self.SelectDate1.setItemText(0, _translate("Movie", "Select date"))
        self.SelectDate1.setItemText(1, _translate("Movie", "Today"))
        self.SelectDate1.setItemText(2, _translate("Movie", "Wed 11 Jul"))
        self.SelectDate1.setItemText(3, _translate("Movie", "Thu 12 Jul"))
        self.SelectDate1.setItemText(4, _translate("Movie", "Fri 13 Jul"))
        self.SelectDate1.setItemText(5, _translate("Movie", "Sat 14 Jul"))
        self.SelectDate1.setItemText(6, _translate("Movie", "Sun 15 Jul"))
        self.SelectDate1.setItemText(7, _translate("Movie", "Mon 16 Jul"))
        self.SelectDate1.setItemText(8, _translate("Movie", "Tue 17 Jul"))
        self.SelectTime1.setItemText(0, _translate("Movie", "Select time/Theatre"))
        self.SelectTime1.setItemText(1, _translate("Movie", "11:30 / Theatre 1"))
        self.SelectTime1.setItemText(2, _translate("Movie", "12:30 / Theatre 2"))
        self.SelectTime1.setItemText(3, _translate("Movie", "14:30 / Theatre 1"))
        self.SelectTime1.setItemText(4, _translate("Movie", "17:30 / Theatre 1"))
        self.SelectTime1.setItemText(5, _translate("Movie", "20:00 / Theatre 2"))
        self.Next_2.setText(_translate("Movie", "NEXT"))
        self.Back.setText(_translate("Movie", "BACK"))
        self.SelectDate2.setItemText(0, _translate("Movie", "Select date"))
        self.SelectDate2.setItemText(1, _translate("Movie", "Today"))
        self.SelectDate2.setItemText(2, _translate("Movie", "Wed 11 Jul"))
        self.SelectDate2.setItemText(3, _translate("Movie", "Thu 12 Jul"))
        self.SelectDate2.setItemText(4, _translate("Movie", "Fri 13 Jul"))
        self.SelectDate2.setItemText(5, _translate("Movie", "Sat 14 Jul"))
        self.SelectDate2.setItemText(6, _translate("Movie", "Sun 15 Jul"))
        self.SelectDate2.setItemText(7, _translate("Movie", "Mon 16 Jul"))
        self.SelectDate2.setItemText(8, _translate("Movie", "Tue 17 Jul"))
        self.SelectTime2.setItemText(0, _translate("Movie", "Select Time/Theatre"))
        self.SelectTime2.setItemText(1, _translate("Movie", "11:30 / Theatre 2"))
        self.SelectTime2.setItemText(2, _translate("Movie", "14:30 / Theatre 2"))
        self.SelectTime2.setItemText(3, _translate("Movie", "17:30 / Theatre 2"))
        self.SelectTime2.setItemText(4, _translate("Movie", "20:00 / Theatre 1"))
        self.Next_3.setText(_translate("Movie", "Next"))
        self.Back_2.setText(_translate("Movie", "BACK"))
        self.checkBox.setText(_translate("Movie", "E1"))
        self.checkBox_2.setText(_translate("Movie", "E2"))
        self.checkBox_3.setText(_translate("Movie", "E3"))
        self.checkBox_4.setText(_translate("Movie", "D1"))
        self.checkBox_5.setText(_translate("Movie", "C1"))
        self.checkBox_6.setText(_translate("Movie", "B1"))
        self.checkBox_7.setText(_translate("Movie", "D2"))
        self.checkBox_8.setText(_translate("Movie", "C2"))
        self.checkBox_9.setText(_translate("Movie", "A1"))
        self.checkBox_10.setText(_translate("Movie", "E4"))
        self.checkBox_11.setText(_translate("Movie", "D3"))
        self.checkBox_12.setText(_translate("Movie", "D4"))
        self.checkBox_13.setText(_translate("Movie", "B2"))
        self.checkBox_14.setText(_translate("Movie", "A2"))
        self.checkBox_15.setText(_translate("Movie", "C3"))
        self.checkBox_16.setText(_translate("Movie", "B3"))
        self.checkBox_17.setText(_translate("Movie", "A3"))
        self.checkBox_18.setText(_translate("Movie", "C4"))
        self.checkBox_19.setText(_translate("Movie", "B4"))
        self.checkBox_20.setText(_translate("Movie", "A4"))
        self.Next_4.setText(_translate("Movie", "NEXT"))
        self.checkBox_41.setText(_translate("Movie", "A5"))
        self.checkBox_42.setText(_translate("Movie", "E5"))
        self.checkBox_43.setText(_translate("Movie", "D5"))
        self.checkBox_44.setText(_translate("Movie", "C5"))
        self.checkBox_45.setText(_translate("Movie", "B5"))
        self.Back_3.setText(_translate("Movie", "BACK"))
        self.checkBox_21.setText(_translate("Movie", "B1"))
        self.checkBox_22.setText(_translate("Movie", "A1"))
        self.checkBox_23.setText(_translate("Movie", "C1"))
        self.checkBox_24.setText(_translate("Movie", "B2"))
        self.checkBox_25.setText(_translate("Movie", "D1"))
        self.checkBox_26.setText(_translate("Movie", "A2"))
        self.checkBox_27.setText(_translate("Movie", "E1"))
        self.checkBox_28.setText(_translate("Movie", "C2"))
        self.checkBox_29.setText(_translate("Movie", "D2"))
        self.checkBox_30.setText(_translate("Movie", "E2"))
        self.checkBox_31.setText(_translate("Movie", "A3"))
        self.checkBox_32.setText(_translate("Movie", "B3"))
        self.checkBox_33.setText(_translate("Movie", "C3"))
        self.checkBox_34.setText(_translate("Movie", "D3"))
        self.checkBox_35.setText(_translate("Movie", "E3"))
        self.checkBox_36.setText(_translate("Movie", "A4"))
        self.checkBox_37.setText(_translate("Movie", "B4"))
        self.checkBox_38.setText(_translate("Movie", "C4"))
        self.checkBox_39.setText(_translate("Movie", "D4"))
        self.checkBox_40.setText(_translate("Movie", "E4"))
        self.Next_5.setText(_translate("Movie", "NEXT"))
        self.Back_4.setText(_translate("Movie", "BACK"))
        self.pushButton_4.setText(_translate("Movie", "DEBIT/CREDIT CARD"))
        self.pushButton_5.setText(_translate("Movie", "Online Payment"))
        self.Credit.setText(_translate("Movie", "CREDIT/DEBIT CARD"))
        self.payment_2.setText(_translate("Movie", "Online Payment"))
        self.Next_6.setText(_translate("Movie", "NEXT"))
        self.Next_7.setText(_translate("Movie", "NEXT"))
        self.Back_6.setText(_translate("Movie", "BACK"))
        self.Next_8.setText(_translate("Movie", "NEXT"))
        self.Back_7.setText(_translate("Movie", "BACK"))
        self.DONE.setText(_translate("Movie", "DONE"))

if __name__=="__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Movie = QtWidgets.QStackedWidget()
    ui = Ui_Movie()
    ui.setupUi(Movie)
    Movie.show()
    #sys.exit(app.exac_())

